name: clean_architecture_tdd_course
description: TDD Clean Architecture for Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it:
  # Bloc for state management
  flutter_bloc:
  # Value equality
  equatable:
  # Functional programming thingies
  dartz:
  # Remote API
  data_connection_checker:
  http:
  # Local cache
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

flutter:
  uses-material-design: true
